[WIP] Add basic support for neovim's built-in LSP
cocopon/iceberg.vim pull request #76
Opened 2020-09-26 04:13 UTC by woodyZootopia

2020-11-09 18:38 UTC, jsdalton commented
Thanks for this! I copied and pasted it into my vim config and I'm blessed with sane looking diagnostic messages. 🙇 

👍  to include this

2020-12-01 05:36 UTC, arthurk commented
looks great! here's a screenshot with the lsp warnings and hover menu

<img width="1159" alt="Screen Shot 2020-12-01 at 1 35 08 PM" src="https://user-images.githubusercontent.com/23406/100701228-2b766a80-33da-11eb-8c99-43aeaf9b94ae.png">

2021-07-25 11:54 UTC, woodyZootopia commented
@cocopon It's been nearly one year since this PR was created, and it seems to be working fine in other people's environments too. I think it's ok to merge this PR to the master branch.

2021-08-04 15:27 UTC, dinhhuy258 commented
Maybe he already forgets about this project ><

2021-11-03 05:25 UTC, mikepqr commented
This is a huge improvement over the current behavior, I'm using it now very happily, and I don't want to argue against merging it.

But I would like to note that this PR makes a fairly opinionated choice to use the same color for hint, warning and information.

The error groups look great in iceberg's red, but I would personally prefer hint, warning and information to not be the same color. This would be more consistent with neovim's defaults. Hint in a grey, warning in an orange and information in a blue would be consistent with neovim defaults. But I don't feel strongly about what colors those diagnostic levels should actually be. My point is that they should be different.

The four levels have meaning, and flattening three of them into a single color loses that. I also think is generally a good idea to make a colorscheme consistent with what neovim/plugin developers expect, unless it defeats the aesthetic goals of the colorscheme completely (which is not the case here IMO).

2021-11-03 13:27 UTC, woodyZootopia commented
@mikepqr Thank you for your opinion. I agree with that.
I added another experimental commit, which uses different colors for warning/info/hint. The coloring is just an experimental one so please (anyone) tell me frankly if there is any issues with that.

2021-11-03 16:18 UTC, mikepqr commented
Thanks! Commented over on #75.

2021-12-25 10:26 UTC, cocopon requested changes
Thank you for your contribution, and sorry for the late reply... Please check the feedback.

2021-12-25 10:26 UTC, cocopon commented on src/iceberg.vim
> +        \ }))
It is deprecated and can be removed.

2021-12-25 10:26 UTC, cocopon commented on src/iceberg.vim
> -  " }}}
Unintentional deletion?

2021-12-25 10:26 UTC, cocopon commented on src/iceberg.vim
> +<<<<<<< HEAD
Could you squash a commit including invalid syntax?

2021-12-27 11:09 UTC, woodyZootopia commented
@cocopon Thank you for your careful comments. Applied them all, and rebased to the latest master.

2021-12-28 00:27 UTC, cocopon approved these changes

2021-12-28 00:52 UTC, merged

2021-12-28 00:58 UTC, cocopon commented
Merged, thank you for your contribution!

Note: I fine-tuned some coloration:
- Hint: Used `comment_fg` instead because `linenr_fg` is not designed for the normal background.
- Info: Used `lblue` instead because it is more readable than `blue`, it has distant hue from the normal background.